import { app, BrowserWindow, ipcMain } from 'electron';
import path from 'path';
import bcrypt from 'bcryptjs';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';
import * as dotenv from 'dotenv';

// setup ESM environment variables (equivalent to __filename and __dirname in CommonJS)
const require = createRequire(import.meta.url);
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// detect if the app is packaged (Production) or running in development
const isProd = app.isPackaged;

// DOTENV CONFIGURATION
// development - it reads from the root .env file.
// production - the .env file must be located in the 'resources' folder
if (isProd) {
  dotenv.config({ path: path.join(process.resourcesPath, '.env') });
} else {
  dotenv.config();
}

// access the database URL from environment variables
const DATABASE_URL = process.env.DATABASE_URL;

// PRISMA PATH SETUP
// define the location of node_modules. In production, Prisma binaries 
// are located in the 'resources' folder to avoid ASAR path issues.
const prismaRoot = isProd 
  ? path.join(process.resourcesPath, 'node_modules')
  : path.join(process.cwd(), 'node_modules');

// dynamically require PrismaClient from the specific root path
const { PrismaClient } = require(path.join(prismaRoot, '@prisma/client'));

// PRISMA CLIENT INITIALIZATION
// manually inject the DATABASE_URL and specify the exact path to the. query Engine binary for production environments.
const prisma = new PrismaClient({
  datasources: { db: { url: DATABASE_URL } },
  ...(isProd && {
    __internal: {
      engine: {
        binaryPath: path.join(prismaRoot, '.prisma/client/query_engine-windows.dll.node')
      }
    }
  })
});

// defines App's ID so Windows recognises the icon in Taskbar
app.setAppUserModelId("com.hammysden.app");

function createWindow() {
  const win = new BrowserWindow({
    width: 450,
    height: 550,
    useContentSize: true,
    resizable: false,       // disables stretching the screen
    maximizable: false,     // disables the maximize button
    fullscreenable: false,  // disables fullscreen
    frame: false,           // disables the default upper bar
    transparent: true,      // for the transparent corners

    icon: path.join(process.cwd(), 'src/renderer/assets/app-icon.ico'), // icon image

    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
      sandbox: false,
    },
  });

  if (isProd) {
    // PRODUCTION MODE: load the index.html file generated by Vite in the 'dist' folder
    // the path is relative to the main.js file located inside 'dist'
    win.loadFile(path.join(__dirname, 'index.html'));
  } else {
    // DEVELOPMENT MODE: load the local development server URL provided by Vite
    win.loadURL('http://localhost:5173');
  }
}

app.whenReady().then(createWindow);

// close app if no windows are open
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});

// for button exit app (closes app)
ipcMain.on('force-close', () => {
  app.quit();
});

// minimize window
ipcMain.on('minimize-app', () => {
  const win = BrowserWindow.getFocusedWindow();
  if (win) win.minimize();
});

// TO-DO LIST
// add tasks
ipcMain.handle('add-task', async (event, taskData) => {
  const user = await prisma.user.findUnique({
    where: { id: taskData.userId },
    select: { userCode: true }
  });

  return await prisma.task.create({
    data: {
      ...taskData,
      userCode: user.userCode
    }
  });
});

// load tasks
ipcMain.handle('get-tasks', async (event, userId) => {
  return await prisma.task.findMany({
    where: { userId },
    orderBy: { position: 'asc' }
  });
});

// update task (check)
ipcMain.handle('update-task', async (event, { id, data }) => {
  return await prisma.task.update({
    where: { id: id },
    data: data
  });
});

// delete task
ipcMain.handle('delete-task', async (event, id) => {
  return await prisma.task.delete({
    where: { id: id }
  });
});

// CALENDAR
// load calendar events
ipcMain.handle('get-events', async (event, userId) => {
  return await prisma.event.findMany({
    where: { userId: userId },
    orderBy: { startDate: 'asc' }
  });
});

// new event
ipcMain.handle('add-event', async (event, eventData) => {
  const user = await prisma.user.findUnique({
    where: { id: eventData.userId },
    select: { userCode: true }
  });

  return await prisma.event.create({
    data: {
      ...eventData,
      userCode: user.userCode
    }
  });
});

// delete event
ipcMain.handle('delete-event', async (event, id) => {
  return await prisma.event.delete({
    where: { id: id }
  });
});

// update task (check)
ipcMain.handle('update-event', async (event, { id, data }) => {
  return await prisma.event.update({
    where: { id: id },
    data: data
  });
});

// TIMER
// save/add session
ipcMain.handle('add-session', async (event, sessionData) => {
  const user = await prisma.user.findUnique({
    where: { id: sessionData.userId },
    select: { userCode: true }
  });

  const session = await prisma.TimerSession.create({
    data: {
      duration: parseInt(sessionData.duration) || 0, // not null
      recipe: sessionData.recipe,
      notes: sessionData.notes,
      userCode: user.userCode,
      // telling Prisma: "connect this session to this user ID"
      user: {connect: { id: sessionData.userId }}
    }
  });
  return session;
});

// update existing session (for History editing)
ipcMain.handle('update-session', async (event, { id, data }) => {
  return await prisma.TimerSession.update({
    where: { id },
    data: data
  });
});

// HISTORY
// get sessions history
ipcMain.handle('get-sessions', async (event, userId) => {
  try {
    return await prisma.timerSession.findMany({
      where: { userId: userId },
      orderBy: { createdAt: 'desc' } // shows the most recents first
    });
  } catch (error) {
    console.error("Erro Prisma (get-sessions):", error);
    throw error;
  }
});

// LOGIN
// create account
ipcMain.handle('auth-signup', async (event, { name, email, password }) => {
  const saltRounds = 10;
  // generates the "hidden" password
  const hashedPassword = await bcrypt.hash(password, saltRounds);

  const generateUserCodeInitials = (fullName) => {
    const words = fullName.trim().toUpperCase().split(/\s+/);
    let initials = '';

    if (words.length >= 2) {
      initials = words[0][0] + words[words.length - 1][0];
    } else if (words.length === 1 && words[0].length >= 2) {
      initials = words[0].substring(0, 2);
    } else {
      initials = 'HM';
    }

    const randomNumber = Math.floor(100 + Math.random() * 900);
    return `${initials}-${randomNumber}`;
  };

  let generatedCode = generateUserCodeInitials(name);
  
  let existCode = await prisma.user.findUnique({ where: { userCode: generatedCode } });
  while (existCode) {
    generatedCode = generateUserCodeInitials(name);
    existCode = await prisma.user.findUnique({ where: { userCode: generatedCode } });
  }

  return await prisma.user.create({
    data: {
      name,
      email,
      password: hashedPassword, // saves the Hash, not the real password
      userCode: generatedCode,
    },
  });
});

// login
ipcMain.handle('auth-login', async (event, { email, password }) => {
  const user = await prisma.user.findUnique({ where: { email } });
  
  if (user) {
    // compares the written password with the saved hash
    const match = await bcrypt.compare(password, user.password);
    if (match) return user;
  }
  
  throw new Error('Access denied');
});

// SETTINGS - ACCOUNT 
// update user email
ipcMain.handle('update-user-email', async (event, { id, email }) => {
  try {
    const cleanEmail = email.trim();

    // verify is another user (different id) already uses this email
    const existingUserWithEmail = await prisma.user.findFirst({
      where: {
        email: cleanEmail,
        id: {
          not: id // different id from this account
        }
      }
    });

    if (existingUserWithEmail) {
      // if founds, error
      throw new Error('Email already in use');
    }

    // if not used, update
    const updatedUser = await prisma.user.update({
      where: { id: id },
      data: { email: cleanEmail }
    });

    // returns updated user
    return updatedUser;

  } catch (error) {
    console.error("Erro Prisma (update-user-email):", error);
    throw new Error(error.message || 'Error updating email');
  }
});